title: Mémoire M2MSR 2023-2024

subtitle:
  "Analyse comparative de la mortalité du cancer du sein entre la région
   Hauts-de-France et le reste de la France métropolitaine : potentiel
   de la réutilisation de données du PMSI/SNDS"

keywords:
  - Cancer du sein
  - Mortalité
  - Hauts-de-France
  - Données massives
  - SNDS
  - Dossier patient informatisé

authors:
  - name: Julien ELICES-DIEZ
    affiliations:
      - name: DES Santé Publique, Université de Lille, Lille, France
      - name: Unité de Méthodologie et de Biostatistique, Centre Oscar Lambret, Lille, France
  - name: Pr. Emmanuel CHAZARD
    affiliation: CERIM, ULR 2694-METRICS, Université de Lille, CHU Lille, Lille, France
  - name: Pr. Nicolas PENEL
    affiliations:
      - name: Département d'Oncologie Médicale, Centre Oscar Lambret, Lille, France
      - name: ULR 2694-METRICS, Université de Lille, CHU Lille, Lille, France

date: 2024-08-30

lang: fr

csl: biblio/nejm.csl
bibliography: biblio/references.bib

format:
  hebstr-html:
    code-tools:
      source: https://github.com/hebstr/m2-man
